spring:
  application:
    name: simple-virus-total
  servlet:
    multipart:
      max-file-size: 650MB
      max-request-size: 651MB
  threads:
    virtual:
      enabled: true
  ai:
    google:
      genai:
        api-key: 1
        chat:
          options:
            temperature: 0
            top-p: 0.8
            model: gemma-4-31b-it

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    layout: BaseLayout

api-key: