spring:
  application:
    name: simple-virus-total
  servlet:
    multipart:
      max-file-size: 650MB
      max-request-size: 651MB
      location: ./temp
  messages:
    basename: i18n/messages
  threads:
    virtual:
      enabled: true
  ai:
    google:
      genai:
        api-key: ${params.google.key:-}
        chat:
          options:
            temperature: 0
            top-p: 0.8
            model: ${params.google.model:gemma-4-31b-it}
            google-search-retrieval: ${params.google.search:false}
            thinking-level: ${params.google.thinking-level:high}

server:
  port: ${params.port:8080}
  tomcat:
    basedir: ./temp/tomcat

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    layout: BaseLayout

vt-key: ${params.v-key}

external-skill:
  enable: ${params.external.enable:false}
  dir: ${params.external.dir:}
  top-limit: ${params.external.top-limit:3}

ai-provider:
  customer: ${params.customer.ai:false}
  base-url: ${params.customer.base-url:}
  api-key: ${params.customer.api-key:}
  model: ${params.customer.model:}
  temperature: ${params.customer.temperature:0}